### ISSUE TITLE
Sugestão: Tratar alguns prints na tela 

### ISSUE THREAD

**Issue by joaocanuto** [All3yp/Phrase-Generator-Challenge#3]
<img width="357" alt="Captura de Tela 2023-05-15 às 20 43 46" src="https://github.com/All3yp/Phrase-Generator-Challenge/assets/83474213/e6461dbe-7468-498c-99a1-e6c9a0f24b63">

Quando peço para gerar uma frase aleatoria, ele ta me retornando de maneira pura o `Optional`. Uma sugestão seria printar apenas o conteúdo.

_Ademais, ficou um projeto, parabéns pelo trabalho!_

**Comment by All3yp** [comment]
Olá, deixamos o código do projeto na develop, a master estava desatualizada, mas o merge já foi feito.
